### ISSUE TITLE
Doesn't work with config on specific vm

### ISSUE THREAD

**Issue by nalipaz** [CodeYellowBV/vagrant-reverse-proxy#1]
I don't think this allows only setting entries for one specific machine in a multi-machine Vagrantfile, that is at least from what I can tell. I have attempted multiple things, but what I would expect to work would be something like:

```
Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

...
  config.vm.define "httpd" do |httpd|
    httpd.vm.provider "docker" do |d|
      d.build_dir = "httpd"
...
      d.name = "#{ENV['SITENAME']}_httpd"
...
      d.ports = ["#{ENV['HTTPPORT']}:80", "#{ENV['HTTPSPORT']}:443"]
...
    httpd.vm.hostname = "#{ENV['SITENAME']}.localdev"
    httpd.vm.reverse_proxy.enabled = true
    httpd.vm.reverse_proxy.vhosts = {
      "#{ENV['SITENAME']}" => {
        :host => "#{ENV['SITENAME']}.localdev",
        :port => "#{ENV['HTTPPORT']}"
      },
    }
  end
...
end

```

*note that lines are edited out of the above code in an attempt to maintain brevity and point out a specific section of code.

**Comment by sjamaan** [comment]
Hi!  Thanks for reporting this issue. We only use single-machine configurations currently, that's why we never noticed this bug.

Can you please try if the current master fixes your issue?

**Comment by nalipaz** [comment]
Hi, I haven't had a moment past couple of days to try it out, but will sometime this week. Thanks and I will let you know if it resolved the issue for me.

**Comment by SpaceK33z** [comment]
@nalipaz, did it fix your issue?

**Comment by nalipaz** [comment]
Truthfully, I have been side-tracked for quite some time and haven't had much time to revisit the project I am using this on. I had a working workaround and kept using that whilst.

**Comment by sjamaan** [comment]
I'm closing this. Feel free to open a new ticket if it still isn't working correctly with the new version.
