### ISSUE TITLE
Add server blocks in addition to location blocks?

### ISSUE THREAD

**Issue by sjamaan** [CodeYellowBV/vagrant-reverse-proxy#5]
Quoting from PR #4:

> I have been running a tweaked version of the plugin to suit our desired development environment at work - the big change being that the plugin generates server blocks of configuration (rather than location blocks).
>
> I was wondering if you had any desire for this behaviour (as a config setting again) or not, and if not, am I okay in publishing my forked version as a gem (fairly new to contributing to OS - not sure about etiquette!)

Can you explain why you need this, or how your setup works?

At work, we'd been using the [vagrant-hostmanager plugin](https://github.com/devopsgroup-io/vagrant-hostmanager) to add custom hostnames to `/etc/hosts` for each of our vagrant boxes. This works fine on the host machine itself, but there's no easy way to make those available to other machines on the network: the local `/etc/hosts` modifications aren't available for DNS lookups of other machines. That's why I created this plugin: each machine already has one hostname (or IP address), and you can use the proxy to reach the guest machine through the host's IP address.

Coming from this angle, I don't really see what the server blocks would add, because you could just use an external IP address for each VM, with hostmanager. No doubt I'm overlooking something though, so if you can explain how you're using this, I could figure out if it's worthwhile to add to this version.

You're free to publish your forked version as a gem, but in general it's more productive to avoid forks, as that dilutes development manpower and makes it harder for users to figure out which version to use.

**Comment by samdjstevens** [comment]
Our setup/problem is very similar to yours - the change is really a cosmetic one. Our goal is to be able to access the VM from the host machine with a chosen dev URL, and to also have this dev URL accessible from all other machines on the network without requiring changes to `/etc/hosts`.

We have a setup on the network where custom DNS entries for `*.[persons-initials].dev` requests are routed to that person's  development (host) machine. This allows `www.example.com.ss.dev` for example to route to my host machine without any `/etc/hosts` changes on anyones machines. 

The only thing left is to have the host nginx proxy to the VMs based on the server name, rather than URI after the host I.P. I appreciate that this is very custom to our setup, so I'm not sure if this should just remain in my fork.

**Comment by sjamaan** [comment]
I see, that's very clever!

I'll have to mull this over. Right now I'm leaning towards just letting the user supply a `proc`/`lambda` to generate the block, which is much more flexible than adding another knob to tune this. What do you think?

**Comment by samdjstevens** [comment]
I was thinking of something similar too - I agree that having the config be more flexible rather than just another setting to make it exactly suit my environment would be better. 

The only downside is that the "magic" behind the scenes now has to be explicitly written (the server block config is about 8-10 lines) in the Vagrantfile, making it less of a "do nothing and it just works" tool.

Our dev environment tools also feature a Vagrantfile generator, so this explicit defining of the nginx config is really not a problem for me, but just thinking in general.

**Comment by samdjstevens** [comment]
@sjamaan I'm happy to put together a PR for this next week to allow an optional lambda for the nginx configuration if you think that would be a good fit?

**Comment by sjamaan** [comment]
I've talked with a colleague about this, and we think a lambda wouldn't be very helpful for exactly the reason you state: the tool doesn't really do that much, and letting the user specify the nginx block is putting 90% of the work of what this tool is doing in the user's hands.

Maybe it's better to bake this into the plugin, and have some sort of way to indicate per hostname whether it should create a vhost (`server`) and/or a path (`location`) entry? I'm just not sure about the best syntax for this. Do you have an idea?

**Comment by samdjstevens** [comment]
Maybe the plugin could actually just write both server _and_ location block by default, with no additional config needed. The two configs don't interfere with each other, so I don't see a problem with this. What do you think?

**Comment by sjamaan** [comment]
The path-based approach requires you to include the file inside a server block. I don't think you can declare any servers in there. I suppose we could have two config file names in the configuration, and if one is `nil` that file doesn't get written. This way we can support both, I think.

One remainin problem: What should happen if you have multiple ports? For instance, for one project we're using a regular HTTP server (which has two hostnames) and a websocket server (also two hostnames), which are both reachable by proxy on the default host, under different paths.

**Comment by samdjstevens** [comment]
In regard to your first point, you're right - the nginx setup on the host machine would have to change to just being a straight include, not placing it inside a server block. I suppose this would be a BC break, so two different generated include files would work nicely.

In regard to your second point - I'm not sure what you mean here - would the port mapping not be more flexible with server blocks?

**Comment by sjamaan** [comment]
OK, so we agree on how to solve the issue.

The second point is about having two ports open under the same hostname, but I guess that doesn't matter, because you can just forward different host names to each of the ports. So never mind about that :)

Would you like to try your hand at a PR for this? If not, I'll do it too, but it might take some time, I'm rather busy at work, and AFAIK you already have the basics working.

**Comment by samdjstevens** [comment]
Yeah no problem, I'll get one in this week hopefully. So just to clarify, the PR would add another config option - `config.reverse_proxy.nginx_servers_config_file` (name?) that can define the path of the file to write the server blocks to.

Should the plugin not write to this file if its not specified/nil? Does it hurt it being written to always like the location config is? I think if both files were always generated it would be simpler for the user to use, what do you think?

Also, ideally the `config.reverse_proxy.nginx_config_file` option would have a better name if this is going to be generated along with a server block config file - but this could break BC - what do you think?

**Comment by sjamaan** [comment]
Having a default location for both files is fine by me.  If a user wants to disable writing to one of those files, they can set its name to nil. The disadvantage would be that the default location of the files wouldn't be correct if nginx lives in a nonstandard place, so now you have to override two locations instead of one.

I don't mind breaking backwards compatibility for the filename, because the option hasn't existed for a long time yet. Therefore, not many people will be using it yet :)
