### ISSUE TITLE
Running on Mac

### ISSUE THREAD

**Issue by pscott-au** [CodeYellowBV/vagrant-reverse-proxy#7]
I am looking to use this on my mac but am currently hacking around with symlinks etc.
Am hoping that will be able to pull request something once have got it all working - any tips let me know.

**Comment by sjamaan** [comment]
Hi! With the most recent version, the file names and commands to run nginx are configurable, so symlink hackery should not be necessary anymore. Have you tried with version 0.3 or later?

**Comment by sjamaan** [comment]
Hi again! I'm closing this ticket because there has been no response to my suggestion for two weeks, and no clear suggestion for improvements.

Please re-open this ticket (or better yet, make a pull request) if these settings are insufficient for whatever reason.
