### ISSUE TITLE
Windows support ?

### ISSUE THREAD

**Issue by jamroks** [CodeYellowBV/vagrant-reverse-proxy#9]
Hi, 

 thanks for the plugin . i would like to know if this plugin work on windows .  before i get into trouble i would rather confirm with you that it's usable on windows. 

Cordialement

**Comment by sjamaan** [comment]
Hi,

I don't use Windows and have never tested Vagrant (or this plugin) on Windows. If you're interested in porting this to Windows, and the changes aren't too invasive, I am open to a pull request. I expect there to be a few UNIXisms that you'd need to translate to Windows: obviously, the default paths for the config files are UNIX paths, and the way NGINX is restarted is pretty OS-specific.

On the other hand, perhaps the new Ubuntu layer in Windows 10 makes this trivial, and the plugin "Just Works"(TM)?

**Comment by jamroks** [comment]
Thanks for the answer, but unfortunately for me, i'm on windows 7. So i guess it's a no go for now, i was in rush for a project i'm working on.  i'll try to see if i can make it work and maybe contribute another time but for now just try to configure everything manualy with nginx. 

thanks

**Comment by jamroks** [comment]
Sorry to come back at this again but , do you have an example vagranfile config with the different option setup so i can start to get a feel on how to configure this next time

**Comment by sjamaan** [comment]
Examples for all the supported options are in the `README`. In practice, you rarely need to set all the available options, so I don't have a real-world project that sets all of them.
